export const FETCH_SINGLE_BOOK_REQ = "FETCH_SINGLE_BOOK_REQ";
export const FETCH_SINGLE_BOOK_SUCCESS = "FETCH_SINGLE_BOOK_SUCCESS";
export const FETCH_SINGLE_BOOK_FAILURE = "FETCH_SINGLE_BOOK_FAILURE";
