export const SEARCH_BOOKS_REQUEST = "SEARCH_BOOKS_REQUEST";
export const SEARCH_BOOKS_SUCCESS = "SEARCH_BOOKS_SUCCESS";
export const SEARCH_BOOKS_FAILURE = "SEARCH_BOOKS_FAILURE";

// storage keys

export const GUTENDEX_SEARCH_RESULTS = "GUTENDEX_SEARCH_RESULTS";
export const GUTENDEX_SEARCH_TERM = "GUTENDEX_SEARCH_TERM";
