export const LOGIN_ATTEMPT = "LOGIN_ATTEMPT";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
