export const LOGIN_ATTEMPT = "LOGIN_ATTEMPT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";

// storage keys

export const GUTENDEX_USER_CREDENTIALS = "GUTENDEX_USER_CREDENTIALS";
export const GUTENDEX_USER_FAVORITES = "GUTENDEX_USER_FAVORITES";
