export const HOME_NEXT_PAGE = "HOME_NEXT_PAGE";
export const HOME_PREVIOUS_PAGE = "HOME_PREVIOUS_PAGE";
export const SEARCH_NEXT_PAGE = "SEARCH_NEXT_PAGE";
export const SEARCH_PREVIOUS_PAGE = "SEARCH_PREVIOUS_PAGE";
export const PAGINATION_RESET = "PAGINATION_RESET";
